# Generated by Django 4.1.4 on 2022-12-23 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='steve', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(default='steve@gmail.com', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='download.jpg', upload_to='profiles/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
