# Generated by Django 4.1.4 on 2022-12-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_name_profile_user_email_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
