# Generated by Django 4.1.4 on 2022-12-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='steve', max_length=50, unique=True),
        ),
    ]
