# Generated by Django 4.1.4 on 2022-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_username_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.CharField(default='steve@gmail.com', max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
