# Generated by Django 4.1.4 on 2022-12-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to='profiles/', verbose_name='Avatar'),
        ),
    ]
