# Generated by Django 4.1.4 on 2023-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='steve', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_email',
            field=models.CharField(default='steve@gmail.com', max_length=50, verbose_name='Email'),
        ),
    ]
