# Generated by Django 4.1.4 on 2022-12-21 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ratingstar_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_written',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post_written',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
