# Generated by Django 4.1.4 on 2022-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_written_date_post_written_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name of subcategory:')),
            ],
        ),
        migrations.AddField(
            model_name='post_written',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='blog.subcategory'),
        ),
    ]
