# Generated by Django 4.1.4 on 2022-12-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subcategory_post_written_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_game', models.CharField(default='Doom', max_length=40, verbose_name='Game title:')),
                ('gameplay_text', models.TextField(default='Fine', max_length=3000, verbose_name='Gameplay description:')),
                ('conclusion_text', models.TextField(default='Fine game', max_length=3000, verbose_name='Conclusion:')),
                ('image_of_game', models.ImageField(upload_to='')),
                ('price', models.SmallIntegerField(default=0, help_text='max 5', verbose_name='Price rating:')),
                ('graphics', models.SmallIntegerField(default=0, help_text='max 5', verbose_name='Graphics rating:')),
                ('levels', models.SmallIntegerField(default=0, help_text='max 5', verbose_name='Levels rating:')),
                ('dificulty', models.SmallIntegerField(default=0, help_text='max 5', verbose_name='Dificulty rating:')),
                ('category', models.ManyToManyField(to='blog.subcategory', verbose_name='Category:')),
            ],
        ),
    ]
