# Generated by Django 4.1.4 on 2022-12-21 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title_of_game'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateField(default=datetime.date.today, help_text="Don't touch it!", verbose_name='Created:'),
        ),
    ]
