# Generated by Django 4.1.4 on 2022-12-22 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_game_options_game_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('all_categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('all_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post_written',
            managers=[
                ('all_posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
                ('all_subcategories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='GameViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddres', models.GenericIPAddressField(default='45.243.82.169')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.game')),
            ],
        ),
    ]
