# Generated by Django 4.1.4 on 2022-12-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_gameviews_post_game_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_written',
            name='subcategory',
        ),
    ]
