# Generated by Django 4.1.4 on 2022-12-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_written_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_written',
            name='content',
            field=models.TextField(default='Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum labore suspendisse ultrices gravida....', verbose_name='Content of post'),
        ),
    ]
