# Generated by Django 4.1.4 on 2022-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postviews_post_written_slug_post_written_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_written',
            name='views',
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
        migrations.AddField(
            model_name='post_written',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
